FEATURE(rawx): Add `openio_rawx_state`
open-io/ansible-role-openio-rawx pull request #25
Opened 2019-11-15 13:17 UTC by cdelgehier

##### SUMMARY

This PR allows to remove an instance rawx
`openio_rawx_state` can be `present` (default) or `absent`

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION

2019-11-15 15:00 UTC, vincent-legoll commented on README.md
> +| `openio_rawx_state` | `present` | If `absent` the configuration will be removed and service will be stop |
stopped

2019-11-27 08:49 UTC, vincent-legoll commented
LGTM

2019-11-28 09:24 UTC, vincent-legoll commented on tasks/main.yml
> +      name: "{{ openio_rawx_type }}-{{ item.1.id | default(item.0) }}"  # calculated
`-{{ item.1.id | default(item.0.id) }}` ?

2019-11-28 09:25 UTC, vincent-legoll commented on tasks/main.yml
> +      id: "{{ item.1.id | default(item.0) }}"  # mandatory
same

2019-11-28 09:26 UTC, vincent-legoll commented on tasks/main.yml
> +  shell: gridinit_cmd restart  {{ openio_rawx_namespace }}-{{ openio_rawx_servicename }}
shell => command

2019-11-28 09:27 UTC, vincent-legoll commented on tasks/offline.yml
> +      shell: gridinit_cmd stop  {{ openio_rawx_namespace }}-{{ openio_rawx_servicename }}
shell => command

2019-11-28 09:28 UTC, vincent-legoll requested changes
LGTM otherwise

2019-11-28 21:44 UTC, cdelgehier commented on tasks/main.yml
> +      name: "{{ openio_rawx_type }}-{{ item.1.id | default(item.0) }}"  # calculated
item.0 doesn't have any key 'id'

2019-11-28 21:45 UTC, merged